// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
. . . . . . . . . f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . f f . . 
. f f f f . . f f f f f f f f f 
. f f f f f f f 1 f f f f f f . 
. . f f f f 1 f 1 f 1 f f f f . 
. . . f f f f 1 f 1 f f f f . . 
. . . . . . f f f f f . . . . . 
. . . . . f f 1 f 1 f f . . . . 
. . . . f f 1 f f f 1 f f . . . 
. . . f f f f f f f f f f . . . 
. . . f f f f f . f f f f f . . 
. . . f f f f . . . f f f f . . 
. . f f f f . . . . . f f f . . 
. . f f . . . . . . . . f f . . 
`;
            case "image2":
            case "myImage0":return img`
..............................................
..............................................
................ffdfdddddffdf.................
.............444ffdffdddfffdf444..............
...........ff4141fffdddddfff1414ff............
..........fff444fffffffffffff444fff...........
.........fffff1fffffffffffffff1fffff..........
.......ffffffffffffffdbdffffffffffffff........
......444ffffffffffffbbbffffffffffff444.......
......4141fffff222fffdbdfff222fffff1414.......
.....f444ffffff222fffbbbfff222ffffff444f......
....fff1fffffff222fffdbdfff222fffffff1fff.....
...fffffffffffffffffffffffffffffffffffffff....
...ffffffffffffddfffffffffffffffffffffffff....
..444ffff222fffffffffdfdfffffffff222ffff444...
..4141fff222ffffffffdbbbdfffff1ff222fff1414...
..444ffff222ffff1ffffbbbfffddf1ff222ffff444...
.ff1fffffffffff1f1ffdbbbdffffffffffffffff1ff..
.fffffffffffdfff1ffffdfdffffffffffffffffffff..
.fffffffffffdfffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffdddfffffffffffffffdddfffffffffff..
.444ff222ffdfffdfffffdddffdffdfffdff222ff444..
.4141f222ffdfffdffdffdfdfffffdfffdff222f1414..
.444ff222ffdfffdffdffdddffbffdfffdff222ff444..
.fffffffffffdddffffffbbbffffffdddfffffffffff..
.ffffffffdbdfffffffffbbbffffffffffffffffffff..
.fffffffffbffffffffffffffffffbfddfffffffffff..
.ffffffffdbdffffffffdfdfdffffffddfffffffffff..
.fffffffffffffbbbfffdddddffffffffffffffff1ff..
..444ffff222ffbbbfffdbbbdfbffffff222ffff444...
..4141fff222ffbbbfffffffffbffffff222fff1414...
..444ffff222fffffffffffffffffffff222ffff444...
...fffffffffffffffffffffffffffffffffffffff....
...fffffffffffffffffffffffffffffffffffffff....
....fffffffffffffffffffffffffffffffff1fff.....
.....fff1ffffff222fbbffddff222ffffff444f......
......f444fffff222fbbddffff222fffff1414.......
......f4141ffff222fffffddff222ffffff444.......
.......444ffffffffffffffffffffffffffff........
.........fffff1fffffffffffffff1fffff..........
..........fff444fffffffffffff444fff...........
...........ff4141f7fdfdfdfff1414ff............
.............444ff7fdfdfdffff444..............
................ffffdddddffff.................
..............................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "Adafruit Boss":
            case "anim1":return [img`
. . . . . . . . . f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . f f . . 
. f f f f . . f f f f f f f f f 
. f f f f f f f 1 f f f f f f . 
. . f f f f 1 f 1 f 1 f f f f . 
. . . f f f f 1 f 1 f f f f . . 
. . . . . . f f f f f . . . . . 
. . . . . f f 1 f 1 f f . . . . 
. . . . f f 1 f f f 1 f f . . . 
. . . f f f f f f f f f f . . . 
. . . f f f f f . f f f f f . . 
. . . f f f f . . . f f f f . . 
. . f f f f . . . . . f f f . . 
. . f f . . . . . . . . f f . . 
`, img`
. . . . . f f . . . . . . . . . 
. . . . . f f f . . . . . . . . 
. . . . . f f f . . . . . . . . 
. . f f . f f f . . . . . . . . 
f f f f f f f f f . . f f f f . 
. f f f f f f 1 f f f f f f f . 
. f f f f 1 f 1 f 1 f f f f . . 
. . f f f f 1 f 1 f f f f . . . 
. . . . . f f f f f . . . . . . 
. . . . f f 1 f 1 f f . . . . . 
. . . f f 1 f f f 1 f f . . . . 
. . . f f f f f f f f f f . . . 
. . f f f f f . f f f f f . . . 
. . f f f f . . . f f f f . . . 
. . f f f . . . . . f f f f . . 
. . f f . . . . . . . . f f . . 
`, img`
. . f f . . . . . . . . f f . . 
. . f f f . . . . . f f f f . . 
. . f f f f . . . f f f f . . . 
. . f f f f f . f f f f f . . . 
. . . f f f f f f f f f f . . . 
. . . f f 1 f f f 1 f f . . . . 
. . . . f f 1 f 1 f f . . . . . 
. . . . . f f f f f . . . . . . 
. . f f f f 1 f 1 f f f f . . . 
. f f f f 1 f 1 f 1 f f f f . . 
. f f f f f f 1 f f f f f f f . 
f f f f f f f f f . . f f f f . 
. . f f . f f f . . . . . . . . 
. . . . . f f f . . . . . . . . 
. . . . . f f f . . . . . . . . 
. . . . . f f . . . . . . . . . 
`, img`
. . f f . . . . . . . . f f . . 
. . f f f f . . . . . f f f . . 
. . . f f f f . . . f f f f . . 
. . . f f f f f . f f f f f . . 
. . . f f f f f f f f f f . . . 
. . . . f f 1 f f f 1 f f . . . 
. . . . . f f 1 f 1 f f . . . . 
. . . . . . f f f f f . . . . . 
. . . f f f f 1 f 1 f f f f . . 
. . f f f f 1 f 1 f 1 f f f f . 
. f f f f f f f 1 f f f f f f . 
. f f f f . . f f f f f f f f f 
. . . . . . . . f f f . f f . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . f f f . . . . . 
. . . . . . . . . f f . . . . . 
`];
            case "Circuit playground express":
            case "anim2":return [img`
..............................................
..............................................
................fffffffffffff.................
.............fffffffffffffffffff..............
...........fffffffffffffffffffffff............
..........fffffffffffffffffffffffff...........
.........fffffffffffffffffffffffffff..........
.......fffffffffffffffffffffffffffffff........
......fffffffffffffffffffffffffffffffff.......
......fffffffffffffffffffffffffffffffff.......
.....fffffffffffffffffffffffffffffffffff......
....fffffffffffffffffffffffffffffffffffff.....
...fffffffffffffffffffffffffffffffffffffff....
...fffffffffffffffffffffffffffffffffffffff....
..fffffffffffffffffffffffffffffffffffffffff...
..fffffffffffffffffffffffffffffffffffffffff...
..fffffffffffffffffffffffffffffffffffffffff...
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
..fffffffffffffffffffffffffffffffffffffffff...
..fffffffffffffffffffffffffffffffffffffffff...
..fffffffffffffffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffffffffffffff....
...fffffffffffffffffffffffffffffffffffffff....
....fffffffffffffffffffffffffffffffffffff.....
.....fffffffffffffffffffffffffffffffffff......
......fffffffffffffffffffffffffffffffff.......
......fffffffffffffffffffffffffffffffff.......
.......fffffffffffffffffffffffffffffff........
.........fffffffffffffffffffffffffff..........
..........fffffffffffffffffffffffff...........
...........fffffffffffffffffffffff............
.............fffffffffffffffffff..............
................fffffffffffff.................
..............................................
`, img`
..............................................
..............................................
................fffffffffffff.................
.............fffffffffffffffffff..............
...........fffffffffffffffffffffff............
..........fffffffffffffffffffffffff...........
.........fffffffffffffffffffffffffff..........
.......fffffffffffffffffffffffffffffff........
......fffffffffffffffffffffffffffffffff.......
......fffffffffffffffffffffffffffffffff.......
.....fffffffffffffffffffffffffffffffffff......
....fffffffffffffffffffffffffffffffffffff.....
...fffffffffffffffffffffffffffffffffffffff....
...fffffffffffffffffffffffffffffffffffffff....
..fffffffffffffffffffffffffffffffffffffffff...
..fffffffffffffffffffffffffffffffffffffffff...
..fffffffffffffffffffffffffffffffffffffffff...
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
..fffffffffffffffffffffffffffffffffffffffff...
..fffffffffffffffffffffffffffffffffffffffff...
..fffffffffffffffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffffffffffffff....
...fffffffffffffffffffffffffffffffffffffff....
....fffffffffffffffffffffffffffffffffffff.....
.....ffffffffff222fffffffff222ffffffffff......
......fffffffff222fffffffff222fffffffff.......
......fffffffff222fffffffff222fffffffff.......
.......fffffffffffffffffffffffffffffff........
.........fffffffffffffffffffffffffff..........
..........fffffffffffffffffffffffff...........
...........fffffffffffffffffffffff............
.............fffffffffffffffffff..............
................fffffffffffff.................
..............................................
`, img`
..............................................
..............................................
................fffffffffffff.................
.............fffffffffffffffffff..............
...........fffffffffffffffffffffff............
..........fffffffffffffffffffffffff...........
.........fffffffffffffffffffffffffff..........
.......fffffffffffffffffffffffffffffff........
......fffffffffffffffffffffffffffffffff.......
......fffffffffffffffffffffffffffffffff.......
.....fffffffffffffffffffffffffffffffffff......
....fffffffffffffffffffffffffffffffffffff.....
...fffffffffffffffffffffffffffffffffffffff....
...fffffffffffffffffffffffffffffffffffffff....
..fffffffffffffffffffffffffffffffffffffffff...
..fffffffffffffffffffffffffffffffffffffffff...
..fffffffffffffffffffffffffffffffffffffffff...
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
..fffffff222fffffffffffffffffffff222fffffff...
..fffffff222fffffffffffffffffffff222fffffff...
..fffffff222fffffffffffffffffffff222fffffff...
...fffffffffffffffffffffffffffffffffffffff....
...fffffffffffffffffffffffffffffffffffffff....
....fffffffffffffffffffffffffffffffffffff.....
.....ffffffffff222fffffffff222ffffffffff......
......fffffffff222fffffffff222fffffffff.......
......fffffffff222fffffffff222fffffffff.......
.......fffffffffffffffffffffffffffffff........
.........fffffffffffffffffffffffffff..........
..........fffffffffffffffffffffffff...........
...........fffffffffffffffffffffff............
.............fffffffffffffffffff..............
................fffffffffffff.................
..............................................
`, img`
..............................................
..............................................
................fffffffffffff.................
.............fffffffffffffffffff..............
...........fffffffffffffffffffffff............
..........fffffffffffffffffffffffff...........
.........fffffffffffffffffffffffffff..........
.......fffffffffffffffffffffffffffffff........
......fffffffffffffffffffffffffffffffff.......
......fffffffffffffffffffffffffffffffff.......
.....fffffffffffffffffffffffffffffffffff......
....fffffffffffffffffffffffffffffffffffff.....
...fffffffffffffffffffffffffffffffffffffff....
...fffffffffffffffffffffffffffffffffffffff....
..fffffffffffffffffffffffffffffffffffffffff...
..fffffffffffffffffffffffffffffffffffffffff...
..fffffffffffffffffffffffffffffffffffffffff...
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffff222fffffffffffffffffffffffffff222fffff..
.fffff222fffffffffffffffffffffffffff222fffff..
.fffff222fffffffffffffffffffffffffff222fffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
..fffffff222fffffffffffffffffffff222fffffff...
..fffffff222fffffffffffffffffffff222fffffff...
..fffffff222fffffffffffffffffffff222fffffff...
...fffffffffffffffffffffffffffffffffffffff....
...fffffffffffffffffffffffffffffffffffffff....
....fffffffffffffffffffffffffffffffffffff.....
.....ffffffffff222fffffffff222ffffffffff......
......fffffffff222fffffffff222fffffffff.......
......fffffffff222fffffffff222fffffffff.......
.......fffffffffffffffffffffffffffffff........
.........fffffffffffffffffffffffffff..........
..........fffffffffffffffffffffffff...........
...........fffffffffffffffffffffff............
.............fffffffffffffffffff..............
................fffffffffffff.................
..............................................
`, img`
..............................................
..............................................
................fffffffffffff.................
.............fffffffffffffffffff..............
...........fffffffffffffffffffffff............
..........fffffffffffffffffffffffff...........
.........fffffffffffffffffffffffffff..........
.......fffffffffffffffffffffffffffffff........
......fffffffffffffffffffffffffffffffff.......
......fffffffffffffffffffffffffffffffff.......
.....fffffffffffffffffffffffffffffffffff......
....fffffffffffffffffffffffffffffffffffff.....
...fffffffffffffffffffffffffffffffffffffff....
...fffffffffffffffffffffffffffffffffffffff....
..fffffff222fffffffffffffffffffff222fffffff...
..fffffff222fffffffffffffffffffff222fffffff...
..fffffff222fffffffffffffffffffff222fffffff...
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffff222fffffffffffffffffffffffffff222fffff..
.fffff222fffffffffffffffffffffffffff222fffff..
.fffff222fffffffffffffffffffffffffff222fffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
..fffffff222fffffffffffffffffffff222fffffff...
..fffffff222fffffffffffffffffffff222fffffff...
..fffffff222fffffffffffffffffffff222fffffff...
...fffffffffffffffffffffffffffffffffffffff....
...fffffffffffffffffffffffffffffffffffffff....
....fffffffffffffffffffffffffffffffffffff.....
.....ffffffffff222fffffffff222ffffffffff......
......fffffffff222fffffffff222fffffffff.......
......fffffffff222fffffffff222fffffffff.......
.......fffffffffffffffffffffffffffffff........
.........fffffffffffffffffffffffffff..........
..........fffffffffffffffffffffffff...........
...........fffffffffffffffffffffff............
.............fffffffffffffffffff..............
................fffffffffffff.................
..............................................
`, img`
..............................................
..............................................
................fffffffffffff.................
.............fffffffffffffffffff..............
...........fffffffffffffffffffffff............
..........fffffffffffffffffffffffff...........
.........fffffffffffffffffffffffffff..........
.......fffffffffffffffffffffffffffffff........
......fffffffffffffffffffffffffffffffff.......
......fffffffff222fffffffff222fffffffff.......
.....ffffffffff222fffffffff222ffffffffff......
....fffffffffff222fffffffff222fffffffffff.....
...fffffffffffffffffffffffffffffffffffffff....
...fffffffffffffffffffffffffffffffffffffff....
..fffffff222fffffffffffffffffffff222fffffff...
..fffffff222fffffffffffffffffffff222fffffff...
..fffffff222fffffffffffffffffffff222fffffff...
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffff222fffffffffffffffffffffffffff222fffff..
.fffff222fffffffffffffffffffffffffff222fffff..
.fffff222fffffffffffffffffffffffffff222fffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
..fffffff222fffffffffffffffffffff222fffffff...
..fffffff222fffffffffffffffffffff222fffffff...
..fffffff222fffffffffffffffffffff222fffffff...
...fffffffffffffffffffffffffffffffffffffff....
...fffffffffffffffffffffffffffffffffffffff....
....fffffffffffffffffffffffffffffffffffff.....
.....ffffffffff222fffffffff222ffffffffff......
......fffffffff222fffffffff222fffffffff.......
......fffffffff222fffffffff222fffffffff.......
.......fffffffffffffffffffffffffffffff........
.........fffffffffffffffffffffffffff..........
..........fffffffffffffffffffffffff...........
...........fffffffffffffffffffffff............
.............fffffffffffffffffff..............
................fffffffffffff.................
..............................................
`, img`
..............................................
..............................................
................ffdfdddddffdf.................
.............444ffdffdddfffdf444..............
...........ff4141fffdddddfff1414ff............
..........fff444fffffffffffff444fff...........
.........fffff1fffffffffffffff1fffff..........
.......ffffffffffffffdbdffffffffffffff........
......444ffffffffffffbbbffffffffffff444.......
......4141fffff222fffdbdfff222fffff1414.......
.....f444ffffff222fffbbbfff222ffffff444f......
....fff1fffffff222fffdbdfff222fffffff1fff.....
...fffffffffffffffffffffffffffffffffffffff....
...ffffffffffffddfffffffffffffffffffffffff....
..444ffff222fffffffffdfdfffffffff222ffff444...
..4141fff222ffffffffdbbbdfffff1ff222fff1414...
..444ffff222ffff1ffffbbbfffddf1ff222ffff444...
.ff1fffffffffff1f1ffdbbbdffffffffffffffff1ff..
.fffffffffffdfff1ffffdfdffffffffffffffffffff..
.fffffffffffdfffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffdddfffffffffffffffdddfffffffffff..
.444ff222ffdfffdfffffdddffdffdfffdff222ff444..
.4141f222ffdfffdffdffdfdfffffdfffdff222f1414..
.444ff222ffdfffdffdffdddffbffdfffdff222ff444..
.fffffffffffdddffffffbbbffffffdddfffffffffff..
.ffffffffdbdfffffffffbbbffffffffffffffffffff..
.fffffffffbffffffffffffffffffbfddfffffffffff..
.ffffffffdbdffffffffdfdfdffffffddfffffffffff..
.fffffffffffffbbbfffdddddffffffffffffffff1ff..
..444ffff222ffbbbfffdbbbdfbffffff222ffff444...
..4141fff222ffbbbfffffffffbffffff222fff1414...
..444ffff222fffffffffffffffffffff222ffff444...
...fffffffffffffffffffffffffffffffffffffff....
...fffffffffffffffffffffffffffffffffffffff....
....fffffffffffffffffffffffffffffffff1fff.....
.....fff1ffffff222fbbffddff222ffffff444f......
......f444fffff222fbbddffff222fffff1414.......
......f4141ffff222fffffddff222ffffff444.......
.......444ffffffffffffffffffffffffffff........
.........fffff1fffffffffffffff1fffff..........
..........fff444fffffffffffff444fff...........
...........ff4141f7fdfdfdfff1414ff............
.............444ff7fdfdfdffff444..............
................ffffdddddffff.................
..............................................
`, img`
..............................................
..............................................
................ffdfdddddffdf.................
.............444ffdffdddfffdf444..............
...........ff4141fffdddddfff1414ff............
..........fff444fffffffffffff444fff...........
.........fffff1fffffffffffffff1fffff..........
.......ffffffffffffffdbdffffffffffffff........
......444ffffffffffffbbbffffffffffff444.......
......4141fffff222fffdbdfff222fffff1414.......
.....f444ffffff222fffbbbfff222ffffff444f......
....fff1fffffff222fffdbdfff222fffffff1fff.....
...fffffffffffffffffffffffffffffffffffffff....
...ffffffffffffddfffffffffffffffffffffffff....
..444ffff222fffffffffdfdfffffffff222ffff444...
..4141fff222ffffffffdbbbdfffff1ff222fff1414...
..444ffff222ffff1ffffbbbfffddf1ff222ffff444...
.ff1fffffffffff1f1ffdbbbdffffffffffffffff1ff..
.fffffffffffdfff1ffffdfdffffffffffffffffffff..
.fffffffffffdfffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffdddfffffffffffffffdddfffffffffff..
.444ff222ffdfffdfffffdddffdffdfffdff222ff444..
.4141f222ffdfffdffdffdfdfffffdfffdff222f1414..
.444ff222ffdfffdffdffdddffbffdfffdff222ff444..
.fffffffffffdddffffffbbbffffffdddfffffffffff..
.ffffffffdbdfffffffffbbbffffffffffffffffffff..
.fffffffffbffffffffffffffffffbfddfffffffffff..
.ffffffffdbdffffffffdfdfdffffffddfffffffffff..
.fffffffffffffbbbfffdddddffffffffffffffff1ff..
..444ffff222ffbbbfffdbbbdfbffffff222ffff444...
..4141fff222ffbbbfffffffffbffffff222fff1414...
..444ffff222fffffffffffffffffffff222ffff444...
...fffffffffffffffffffffffffffffffffffffff....
...fffffffffffffffffffffffffffffffffffffff....
....fffffffffffffffffffffffffffffffff1fff.....
.....fff1ffffff222fbbffddff222ffffff444f......
......f444fffff222fbbddffff222fffff1414.......
......f4141ffff222fffffddff222ffffff444.......
.......444ffffffffffffffffffffffffffff........
.........fffff1fffffffffffffff1fffff..........
..........fff444fffffffffffff444fff...........
...........ff4141f7fdfdfdfff1414ff............
.............444ff7fdfdfdffff444..............
................ffffdddddffff.................
..............................................
`, img`
..............................................
..............................................
................ffdfdddddffdf.................
.............444ffdffdddfffdf444..............
...........ff4141fffdddddfff1414ff............
..........fff444fffffffffffff444fff...........
.........fffff1fffffffffffffff1fffff..........
.......ffffffffffffffdbdffffffffffffff........
......444ffffffffffffbbbffffffffffff444.......
......4141fffff222fffdbdfff222fffff1414.......
.....f444ffffff222fffbbbfff222ffffff444f......
....fff1fffffff222fffdbdfff222fffffff1fff.....
...fffffffffffffffffffffffffffffffffffffff....
...ffffffffffffddfffffffffffffffffffffffff....
..444ffff222fffffffffdfdfffffffff222ffff444...
..4141fff222ffffffffdbbbdfffff1ff222fff1414...
..444ffff222ffff1ffffbbbfffddf1ff222ffff444...
.ff1fffffffffff1f1ffdbbbdffffffffffffffff1ff..
.fffffffffffdfff1ffffdfdffffffffffffffffffff..
.fffffffffffdfffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffdddfffffffffffffffdddfffffffffff..
.444ff222ffdfffdfffffdddffdffdfffdff222ff444..
.4141f222ffdfffdffdffdfdfffffdfffdff222f1414..
.444ff222ffdfffdffdffdddffbffdfffdff222ff444..
.fffffffffffdddffffffbbbffffffdddfffffffffff..
.ffffffffdbdfffffffffbbbffffffffffffffffffff..
.fffffffffbffffffffffffffffffbfddfffffffffff..
.ffffffffdbdffffffffdfdfdffffffddfffffffffff..
.fffffffffffffbbbfffdddddffffffffffffffff1ff..
..444ffff222ffbbbfffdbbbdfbffffff222ffff444...
..4141fff222ffbbbfffffffffbffffff222fff1414...
..444ffff222fffffffffffffffffffff222ffff444...
...fffffffffffffffffffffffffffffffffffffff....
...fffffffffffffffffffffffffffffffffffffff....
....fffffffffffffffffffffffffffffffff1fff.....
.....fff1ffffff222fbbffddff222ffffff444f......
......f444fffff222fbbddffff222fffff1414.......
......f4141ffff222fffffddff222ffffff444.......
.......444ffffffffffffffffffffffffffff........
.........fffff1fffffffffffffff1fffff..........
..........fff444fffffffffffff444fff...........
...........ff4141f7fdfdfdfff1414ff............
.............444ff7fdfdfdffff444..............
................ffffdddddffff.................
..............................................
`, img`
..............................................
..............................................
................ffdfdddddffdf.................
.............444ffdffdddfffdf444..............
...........ff4141fffdddddfff1414ff............
..........fff444fffffffffffff444fff...........
.........fffff1fffffffffffffff1fffff..........
.......ffffffffffffffdbdffffffffffffff........
......444ffffffffffffbbbffffffffffff444.......
......4141fffff222fffdbdfff222fffff1414.......
.....f444ffffff222fffbbbfff222ffffff444f......
....fff1fffffff222fffdbdfff222fffffff1fff.....
...fffffffffffffffffffffffffffffffffffffff....
...ffffffffffffddfffffffffffffffffffffffff....
..444ffff222fffffffffdfdfffffffff222ffff444...
..4141fff222ffffffffdbbbdfffff1ff222fff1414...
..444ffff222ffff1ffffbbbfffddf1ff222ffff444...
.ff1fffffffffff1f1ffdbbbdffffffffffffffff1ff..
.fffffffffffdfff1ffffdfdffffffffffffffffffff..
.fffffffffffdfffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffdddfffffffffffffffdddfffffffffff..
.444ff222ffdfffdfffffdddffdffdfffdff222ff444..
.4141f222ffdfffdffdffdfdfffffdfffdff222f1414..
.444ff222ffdfffdffdffdddffbffdfffdff222ff444..
.fffffffffffdddffffffbbbffffffdddfffffffffff..
.ffffffffdbdfffffffffbbbffffffffffffffffffff..
.fffffffffbffffffffffffffffffbfddfffffffffff..
.ffffffffdbdffffffffdfdfdffffffddfffffffffff..
.fffffffffffffbbbfffdddddffffffffffffffff1ff..
..444ffff222ffbbbfffdbbbdfbffffff222ffff444...
..4141fff222ffbbbfffffffffbffffff222fff1414...
..444ffff222fffffffffffffffffffff222ffff444...
...fffffffffffffffffffffffffffffffffffffff....
...fffffffffffffffffffffffffffffffffffffff....
....fffffffffffffffffffffffffffffffff1fff.....
.....fff1ffffff222fbbffddff222ffffff444f......
......f444fffff222fbbddffff222fffff1414.......
......f4141ffff222fffffddff222ffffff444.......
.......444ffffffffffffffffffffffffffff........
.........fffff1fffffffffffffff1fffff..........
..........fff444fffffffffffff444fff...........
...........ff4141f7fdfdfdfff1414ff............
.............444ff7fdfdfdffff444..............
................ffffdddddffff.................
..............................................
`, img`
..............................................
..............................................
................ffdfdddddffdf.................
.............444ffdffdddfffdf444..............
...........ff4141fffdddddfff1414ff............
..........fff444fffffffffffff444fff...........
.........fffff1fffffffffffffff1fffff..........
.......ffffffffffffffdbdffffffffffffff........
......444ffffffffffffbbbffffffffffff444.......
......4141fffff222fffdbdfff222fffff1414.......
.....f444ffffff222fffbbbfff222ffffff444f......
....fff1fffffff222fffdbdfff222fffffff1fff.....
...fffffffffffffffffffffffffffffffffffffff....
...ffffffffffffddfffffffffffffffffffffffff....
..444ffff222fffffffffdfdfffffffff222ffff444...
..4141fff222ffffffffdbbbdfffff1ff222fff1414...
..444ffff222ffff1ffffbbbfffddf1ff222ffff444...
.ff1fffffffffff1f1ffdbbbdffffffffffffffff1ff..
.fffffffffffdfff1ffffdfdffffffffffffffffffff..
.fffffffffffdfffffffffffffffffffffffffffffff..
.fffffffffffffffffffffffffffffffffffffffffff..
.fffffffffffdddfffffffffffffffdddfffffffffff..
.444ff222ffdfffdfffffdddffdffdfffdff222ff444..
.4141f222ffdfffdffdffdfdfffffdfffdff222f1414..
.444ff222ffdfffdffdffdddffbffdfffdff222ff444..
.fffffffffffdddffffffbbbffffffdddfffffffffff..
.ffffffffdbdfffffffffbbbffffffffffffffffffff..
.fffffffffbffffffffffffffffffbfddfffffffffff..
.ffffffffdbdffffffffdfdfdffffffddfffffffffff..
.fffffffffffffbbbfffdddddffffffffffffffff1ff..
..444ffff222ffbbbfffdbbbdfbffffff222ffff444...
..4141fff222ffbbbfffffffffbffffff222fff1414...
..444ffff222fffffffffffffffffffff222ffff444...
...fffffffffffffffffffffffffffffffffffffff....
...fffffffffffffffffffffffffffffffffffffff....
....fffffffffffffffffffffffffffffffff1fff.....
.....fff1ffffff222fbbffddff222ffffff444f......
......f444fffff222fbbddffff222fffff1414.......
......f4141ffff222fffffddff222ffffff444.......
.......444ffffffffffffffffffffffffffff........
.........fffff1fffffffffffffff1fffff..........
..........fff444fffffffffffff444fff...........
...........ff4141f7fdfdfdfff1414ff............
.............444ff7fdfdfdffff444..............
................ffffdddddffff.................
..............................................
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
